---
title: "Day 3 - Conditionals and Loops"
author: "Lewis White"
date: "2022-08-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(palmerpenguins)
```

### `if` statements

```{r}
burrito <- 2.4

if (burrito > 2) {
  print("I love burritos")
  }
```

## example of str_detect and if operator

```{r}
my_ships <- c("Millenium Falcon", "X-Wing", "Tie-Fighter", "Death Star")

str_detect(my_ships, pattern = "in")

phrase <- "I love burritos"

if (str_detect(phrase, "love")) {
  print("I am a burrito fan.")
}
```

```{r}
```



```{r}
pika <- 89.1

if (pika > 60) {
  print("Mega Pika")
} else {
  print("normal pika")
}
```

```{r}
marmot <- 2.8

if (marmot < 0.5) {
  print("This is a small marmot")
} else if (marmot >= 0.5 & marmot < 3) {
  print("this is a medium marmot")
} else {
  print("This is a massive marmot")
}
```




## Example of `%in%` operator

```{r}
tatooine_characters <- starwars |>
  filter(homeworld == "Tatooine")
  
# Use the %in% operator to check for multiple positive matches 
tattooine_endor_naboo <- starwars |>
  filter(homeworld %in% c("Tatooine", "Naboo", "Endor"))

# does the value in the homeworld variable for that row exist IN that vector c("Tatooine", "Naboo", "Endor"). This is faster than the below version.
  
tattooine_endor_naboo <- starwars |>
  filter(homeworld == "Tatooine" |
           homeworld == "Endor" |
           homeworld == "Naboo")

```


```{r}
mean_mtcars <- vector(mode = "numeric", length = ncol(mtcars)) #empty vector expecting numeric values where #columns is same as mtcars

for (i in seq_along(mtcars)) { #for i in 1, 2, 3 ...., 10, 11
  mean_val <- mean(mtcars[[i]], na.rm = TRUE) #stores intermediate mean value. takes mean of all values in the first column. 
  mean_mtcars[i] <- mean_val
}

mean_mtcars
```


```{r}
for (i in seq_along(penguins)) {
  if (is.numeric(penguins[[i]])) {
    penguin_med <- median(penguins[[i]], na.rm = TRUE)
    print(penguin_med)
  }
}
```



```{r}
tree_height <- c(1, 2, 6, 10, 14, 20)

for (i in seq_along(tree_height)) {
  val = tree_height[i] + tree_height[i + 1]
  print(val)
}
```

```{r}
species <- c("dog", "elephant", "goat", "dog", "elephant", "dog")

age_human <- c(3, 8, 4, 6, 12, 18)

animal_ages_vector <- vector(mode = "numeric", length = length(species))

for (i in seq_along(species)) {
  if (species[i] == "dog") {
    animal_age <- age_human[i] * 7
  } else if (species[i] == "elephant") {
    animal_age <- age_human[i] * 0.88
  } else if (species[i] == "goat") {
    goat_age <- age_human[i] * 4.7
  }
  animal_ages_vector[i] <- animal_age
}

```


### for loops across data frames 

```{r}
mean_mtcars <- vector(mode = "numeric", length = ncol(mtcars))

for (i in 1:ncol(mtcars)) {
  mean_val <- mean(mtcars[[i]], na.rm = TRUE)
  mean_mtcars[i] <- mean_val
}

mean_mtcars
```


### functional programming examples

adding syntactic sugar (apply, across, map_df)

```{r}
apply(X = mtcars, MARGIN = 2, FUN = mean)
```

PURRR

```{r}
map(.x = mtcars, .f = mean)
map_df(.x = mtcars, .f = mean)
```



### apply function and tapply

```{r}
apply(mtcars, 2, mean) #data, row (1) or column (2), function
```

### dplyr(across)

```{r}
penguins |>
  mutate(across(c(species, island), tolower))
```

## `group_by() %>% smmmarise` 

```{r}
penguins %>%
  group_by(species, island) %>%
  summarize(mean_bill_length = mean(bill_length_mm, na.rm = TRUE),
            st_bill_length = sd(bill_length_mm, na.rm = TRUE),
            n = n()) ## INCLUDES NA VALUES. REPORTS EVERYTHING



#1. find the mean and sd of character height in `starwars` grouped by homeworld

starwars %>% 
  group_by(homeworld) %>%
      summarise(mean_height = mean(height, na.rm = TRUE),
            sd_height = sd(height, na.rm = TRUE),
            n = n())
  
# tried to filter so n(homeworld) > 1
starwars %>% 
  group_by(homeworld) %>%
  filter(n(homeworld) > 1) %>%
      summarise(mean_height = mean(height, na.rm = TRUE),
            sd_height = sd(height, na.rm = TRUE),
            n = n())


#2. find the maximum, minimum flipper length and samples size for each species of the penguins. 

penguins |> 
  group_by(species, sex) |> 
  summarise(max_flipper = max(flipper_length_mm, na.rm = TRUE),
            min_flipper = min(flipper_length_mm, na.rm = TRUE),
            n = n())


tet_penguin <- penguins |> 
  group_by(species) |> 
  summarise(across(where(is.numeric), c(mean, sd), na.rm = TRUE))
```




